build:
  maxIssues: 0

style:
  MagicNumber:
    active: false
  ReturnCount:
    active: false
  ThrowsCount:
    active: false
  WildcardImport:
    active: false

complexity:
  LongMethod:
    active: true
    threshold: 90
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false
  CyclomaticComplexMethod:
    active: true
    threshold: 20

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false

potential-bugs:
  active: true

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  SleepInsteadOfDelay:
    active: true

naming:
  active: true

comments:
  active: false
